//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLStartingProject.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLStartingProject.Resx.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit.
        /// </summary>
        public static string AddEdit {
            get {
                return ResourceManager.GetString("AddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Grade.
        /// </summary>
        public static string AddEditGrade {
            get {
                return ResourceManager.GetString("AddEditGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User....
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? All grades for this student will be permanently deleted!.
        /// </summary>
        public static string AdminDeletionQuestionStudents {
            get {
                return ResourceManager.GetString("AdminDeletionQuestionStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? All grades for this subject will be permanently deleted!.
        /// </summary>
        public static string AdminDeletionQuestionSubjects {
            get {
                return ResourceManager.GetString("AdminDeletionQuestionSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields must be completed.
        /// </summary>
        public static string AllFieldsStatement {
            get {
                return ResourceManager.GetString("AllFieldsStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the language will log you out!.
        /// </summary>
        public static string ChangeLaguageStatement {
            get {
                return ResourceManager.GetString("ChangeLaguageStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Identification Number.
        /// </summary>
        public static string CNP {
            get {
                return ResourceManager.GetString("CNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only numbers!.
        /// </summary>
        public static string CNPErrorStatement {
            get {
                return ResourceManager.GetString("CNPErrorStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by Paul Gui.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion.
        /// </summary>
        public static string Deletion {
            get {
                return ResourceManager.GetString("Deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? All grades for this student will be deleted!.
        /// </summary>
        public static string DeletionQuestionStudents {
            get {
                return ResourceManager.GetString("DeletionQuestionStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? All grades for this subject will be deleted!.
        /// </summary>
        public static string DeletionQuestionSubjects {
            get {
                return ResourceManager.GetString("DeletionQuestionSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application helps organize students, subjects and grades and makes calculating averages easier.
        /// </summary>
        public static string DescriptionStatement {
            get {
                return ResourceManager.GetString("DescriptionStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and password!.
        /// </summary>
        public static string EmptyUsernamePasswordStatement {
            get {
                return ResourceManager.GetString("EmptyUsernamePasswordStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam already exists!.
        /// </summary>
        public static string ExamExistsStatement {
            get {
                return ResourceManager.GetString("ExamExistsStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have encounterend an error. Please call application administrator for support(&quot;About&quot; section)..
        /// </summary>
        public static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Average.
        /// </summary>
        public static string GeneralAverage {
            get {
                return ResourceManager.GetString("GeneralAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade added succesfully!.
        /// </summary>
        public static string GradeAddedStatement {
            get {
                return ResourceManager.GetString("GradeAddedStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade updated successfully!.
        /// </summary>
        public static string GradeEditedStatement {
            get {
                return ResourceManager.GetString("GradeEditedStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades.
        /// </summary>
        public static string Grades {
            get {
                return ResourceManager.GetString("Grades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Exam.
        /// </summary>
        public static string HasExam {
            get {
                return ResourceManager.GetString("HasExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password please try again!.
        /// </summary>
        public static string IncorrectCredentialsStatement {
            get {
                return ResourceManager.GetString("IncorrectCredentialsStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Exam.
        /// </summary>
        public static string IsExam {
            get {
                return ResourceManager.GetString("IsExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password!.
        /// </summary>
        public static string NullPasswordStatement {
            get {
                return ResourceManager.GetString("NullPasswordStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password cannot be empty!.
        /// </summary>
        public static string NullUsernamePasswordStatement {
            get {
                return ResourceManager.GetString("NullUsernamePasswordStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username!.
        /// </summary>
        public static string NullUsernameStatement {
            get {
                return ResourceManager.GetString("NullUsernameStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoration.
        /// </summary>
        public static string Restoration {
            get {
                return ResourceManager.GetString("Restoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to restore this record?.
        /// </summary>
        public static string RestorationQuestion {
            get {
                return ResourceManager.GetString("RestorationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        public static string Romanian {
            get {
                return ResourceManager.GetString("Romanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row edited successfully!.
        /// </summary>
        public static string RowEditStatement {
            get {
                return ResourceManager.GetString("RowEditStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Management App.
        /// </summary>
        public static string SchoolManagementApp {
            get {
                return ResourceManager.GetString("SchoolManagementApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a grade!.
        /// </summary>
        public static string SelectGradeStatement {
            get {
                return ResourceManager.GetString("SelectGradeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student added successfully: .
        /// </summary>
        public static string StudentAddedStatement {
            get {
                return ResourceManager.GetString("StudentAddedStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject added succesfully: .
        /// </summary>
        public static string SubjectAddedStatement {
            get {
                return ResourceManager.GetString("SubjectAddedStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Name.
        /// </summary>
        public static string SubjectName {
            get {
                return ResourceManager.GetString("SubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        public static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck IsExam checkbox in Grades before unchecking HasExam checkbox!.
        /// </summary>
        public static string UncheckHasExamStatement {
            get {
                return ResourceManager.GetString("UncheckHasExamStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User added successfuly..
        /// </summary>
        public static string UserAddedStatement {
            get {
                return ResourceManager.GetString("UserAddedStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and password must both be longer than 3 characters!.
        /// </summary>
        public static string UsernamePasswordStatement {
            get {
                return ResourceManager.GetString("UsernamePasswordStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
